POST http://localhost:3000/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDZkNjRlMDQ4ZDMzZDQ0ZjA2NGFlNmYiLCJuYW1lIjoiUHJhc2hhbnQgU2luZ2giLCJlbWFpbCI6InByYXNoYW50Y28xMTFAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMS0wNC0wN1QwNzo1MzowNC43NjhaIiwidXBkYXRlZEF0IjoiMjAyMS0wNC0wN1QwNzo1MzowNC43NjhaIiwiX192IjowLCJpYXQiOjE2MTc3OTE2MDMsImV4cCI6MTYxNzc5NTIwM30.FPNkYlL0prtOkJwDtVNqpkHjipdw96CjZUXmoqNWFvk

### 
GET http://localhost:3000/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDZkNjRlMDQ4ZDMzZDQ0ZjA2NGFlNmYiLCJuYW1lIjoiUHJhc2hhbnQgU2luZ2giLCJlbWFpbCI6InByYXNoYW50Y28xMTFAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMS0wNC0wN1QwNzo1MzowNC43NjhaIiwidXBkYXRlZEF0IjoiMjAyMS0wNC0wN1QwNzo1MzowNC43NjhaIiwiX192IjowLCJpYXQiOjE2MTgwMzQ3OTMsImV4cCI6MTYxODAzODM5M30.yDy2OZiHCgXLp-RMnK5Vnff-PBflmgn5F2s2wmD_E_8